# - Find libCrypto
# Find the native OpenSSL LIBCRYPTO includes and library
#
#  LIBCRYPTO_INCLUDE_DIR - where to find sha.h, etc.
#  LIBCRYPTO_LIBRARIES   - List of libraries when using libCrypto.
#  LIBCRYPTO_FOUND       - True if libCrypto found.

find_path(LIBCRYPTO_INCLUDE_DIR NAMES openssl/sha.h PATHS ${CONAN_INCLUDE_DIRS_OPENSSL})
find_library(LIBCRYPTO_LIBRARY NAMES ${CONAN_LIBS_OPENSSL} PATHS ${CONAN_LIB_DIRS_OPENSSL})

if (OPENSSL_FOUND)
    MESSAGE("** LIBCRYPTO ALREADY FOUND BY CONAN!")
    SET(LIBCRYPTO_FOUND TRUE)
    MESSAGE("** FOUND LIBCRYPTO:  ${LIBCRYPTO_LIBRARY}")
    MESSAGE("** FOUND LIBCRYPTO INCLUDE:  ${LIBCRYPTO_INCLUDE_DIR}")
    
    set(LIBCRYPTO_INCLUDE_DIRS ${LIBCRYPTO_INCLUDE_DIR})
    set(LIBCRYPTO_LIBRARIES ${LIBCRYPTO_LIBRARY})
    
    mark_as_advanced(LIBCRYPTO_LIBRARY LIBCRYPTO_INCLUDE_DIR)
endif()
